#spring:
#  redis:
#    cluster:
#      nodes:
#        - gpay.godfunc.fun:6379
#        - gpay.godfunc.fun:6379
#        - gpay.godfunc.fun:6379
#    password:
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
spring:
  redis:
    host: gpay.godfunc.fun
    port: 6379