server:
  port: 9090
  servlet:
    context-path: /api
spring:
  application:
    name: gpay-pay
  datasource:
    url: jdbc:mysql://node1:3306/gpay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  global-config:
    workerId: 1
    dataCenterId: 1

goPayUrl: /goPay/
fixChannelFloatMillis: 2000