server:
  port: 8090
  servlet:
    context-path: /manage
spring:
  application:
    name: gpay-manage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://gpay.godfunc.fun:3306/gpay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
  global-config:
    workerId: 7
    dataCenterId: 1