server:
  port: 9090
  servlet:
    context-path: /api
spring:
  application:
    name: gpay-pay
  datasource:
    url: jdbc:mysql://192.168.31.61:3306/gpay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    workerId: 1
    dataCenterId: 1

goPayUrl: /goPay/
fixChannelFloatMillis: 2000 # 订单过期后，延时多久回滚风控限额 单位毫秒
orderExpiredTime: 1200 # 订单过期时间 单位秒