server:
  port: 9060
spring:
  application:
    name: gpay-merchant-notify
  datasource:
    url: jdbc:mysql://192.168.31.61:3306/gpay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    workerId: 3
    dataCenterId: 1

firstDelayNotifyMillis: 5000